### ISSUE TITLE
Decide on final test export API

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-provider-corner#11]
This provider needs to export its tests in a way suitable for testing other projects. Decide whether we're doing it the current `TestAccTests` way, and how that works for non-SDKv2 providers.

Also fix individual test case logging and debugging.

**Comment by bflad** [comment]
I think we wound up with separate `internal/` directories, which upstream can execute `TF_ACC=1 go test -v ./internal/XXX` as appropriate.
