### ISSUE TITLE
Add a data source with unstable ID and using Default/DefaultFunc

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-provider-corner#2]
Reportedly you get a perma-diff if you use an unstable ID for a data source (see #1) and have a Default/DefaultFunc field set on the data source.

**Comment by bflad** [comment]
(Closing issues that likely won't get actioned anytime soon.) This is not an issue in terraform-plugin-framework. We can reopen if the external acceptance testing is required.
