### ISSUE TITLE
Add a resource that returns an error during Update

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-provider-corner#6]
It would be great to get to the bottom of hashicorp/terraform-plugin-sdk#476 and have a terraform-plugin-go reproduction (if one exists) so we can isolate whether it's a core or SDK problem. But that's a big behavior to change under people, so we should be testing that it stays consistent.

**Comment by bflad** [comment]
(Closing issues that likely won't get actioned anytime soon.) This is handled via unit testing in terraform-plugin-framework. We can reopen if the external acceptance testing is required.
